Added fixes for Julia 1.0
JuliaGraphs/LightGraphsFlows.jl pull request #19
Opened 2018-08-27 02:47 UTC by simonschoelly

Most of the stuff works, but the package `Clp.jl` is not yet ready for version 1.0. Therefore the tests fail and `mincost_flow` does not work yet.

Should also remove most of the warnings in #18

2018-08-27 08:03 UTC, matbesancon commented
oh wonderful thanks! 
For the parametric functions I'm not sure SimpleTraits.jl supports the `where` syntax

2018-08-27 08:12 UTC, matbesancon commented
Also, I think we can change the travis config:
```
julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
- julia: nightly
```

2018-08-27 10:57 UTC, simonschoelly commented
I changed the travis config. There is also appveyor config that defaults to version 0.6 but I'm not familiar with that. 
SimpleTraits does support the `where` syntax, you just have to be a bit careful when you have multiple arguments in the where clause.

2018-08-27 11:55 UTC, matbesancon commented
To update appveyor if you can: https://github.com/JuliaCI/Appveyor.jl
The readme example is up to date for 1.0, copy-pasting should just work, uncomment the nightly fail allowed and we're god

2018-08-27 15:41 UTC, simonschoelly commented
Appveyor is running now but Windows has problems with clp on all versions. The other tests all pass:
https://ci.appveyor.com/project/simonschoelly/lightgraphsflows-jl/build/1.0.10

2018-08-27 15:51 UTC, matbesancon commented
yes clp is supposedly good on 0.7, not sure about 1.0 they didn't put it in their CI scripts, I'll PR them for it

2018-08-27 15:54 UTC, matbesancon commented
https://github.com/JuliaOpt/Clp.jl/pull/32

2018-08-29 15:59 UTC, juliohm commented
Thank you @simonschoelly for your work. What is the status?

2018-08-29 16:33 UTC, simonschoelly commented
Until Clp.jl and Cbc.jl, which is a dependency for the former, work on 1.0, the tests can't pass.

See JuliaOpt/Clp.jl#31 and JuliaOpt/Cbc.jl#54.

2018-09-20 03:03 UTC, simonschoelly commented
Clp runs on Julia v1.0 now, so this PR could probably be merged.

2018-09-20 08:16 UTC, matbesancon requested changes

2018-09-20 08:16 UTC, matbesancon commented on REQUIRE
>  LightGraphs 0.12
should we up LightGraphs to v1.1?

2018-09-20 10:17 UTC, matbesancon approved these changes

2018-09-20 10:17 UTC, matbesancon commented
Wonderful, merging as soon as CI passes, thanks @simonschoelly !

2018-09-20 13:15 UTC, merged